name: CI/CD for Node.js API

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Zip and prepare for deployment
        run: zip -r function.zip .

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code --function-name api-node-student-mateo --zip-file fileb://function.zip
          
      # Paso para enviar una notificación si ocurre un fallo en el despliegue
      - name: Send email notification on failure
        if: failure()  # Solo ejecuta si el trabajo falla
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: |
          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer $SENDGRID_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
                "personalizations": [{
                  "to": [{"email": "'$TO_EMAIL'"}],
                  "subject": "GitHub Actions Job Failed: Deploy to Lambda"
                }],
                "from": {"email": "'$FROM_EMAIL'"},
                "content": [{
                  "type": "text/plain",
                  "value": "El flujo de trabajo en GitHub Actions falló durante el despliegue a Lambda. Por favor revisa los detalles en la pestaña de Actions en GitHub."
                }]
              }'
